linesTileTraceDefaults <- function(x=NULL,
                                   y=NULL,
                                   top=NULL,
                                   right=NULL,
                                   attachToTop=NULL,
                                   attachToRight=NULL,
                                   xdatalimits=c("x"),
                                   ydatalimits=c("y"),
                                   xtransform=c("x"),
                                   ytransform=c("y"),
                                   graphic="lines",
                                   plot=NULL,
                                   layer=10,
                                   markers=FALSE,
                                   labels=NULL,
                                   labelsxoffset=0,
                                   labelsyoffset=0,
                                   color=color,
                                   fill="transparent",
                                   col="black",
                                   lty="solid",
                                   lwd=1,
                                   cex=1,
                                   fontsize=12,
                                   lineheight=1.2,
                                   font=1,
                                   fontfamily="",
                                   fontface="plain",
                                   alpha=0.8,                   # only if pdf
                                   lineend="round",
                                   linejoin="round",
                                   linemitre=10,
                                   lex=1,
                                   pch=1,
                                   size=1,
                                   addArrow=FALSE,
                                   angleArrow=30,
                                   lengthArrow=unit(0.25, "inches"),
                                   endsArrow="last",
                                   typeArrow="open",
                                   just="centre",
                                   hjust=NULL,
                                   vjust=NULL,
                                   rot=0,
                                   check.overlap=FALSE,
                                   clip="on"
                                   ) {

        color <- list(data=NULL,
                  bins=NULL,
                  breaks=NULL,
                  colorset="sequential",# rainbow, diverge, heatmap, terrain, categories
                  hue=NULL,
                  chroma=NULL,
                  luminance=NULL,
                  power=NULL,
                  gamma=2.4,
                  fixup=TRUE
                  )

  
    defaults <- list(x=x,
                     y=y,
                     top=top,
                     right=right,
                     attachToTop=attachToTop,
                     attachToRight=attachToRight,
                     xdatalimits=xdatalimits,
                     ydatalimits=ydatalimits,
                     xtransform=xtransform,
                     ytransform=ytransform,
                     graphic=graphic,
                     plot=plot,
                     layer=layer,
                     markers=markers,
                     labels=labels,
                     labelsxoffset=labelsxoffset,
                     labelsyoffset=labelsyoffset,
                     color=color,
                     fill=fill,
                     col=col,
                     lty=lty,
                     lwd=lwd,
                     cex=cex,
                     fontsize=fontsize,
                     lineheight=lineheight,
                     font=font,
                     fontfamily=fontfamily,
                     fontface=fontface,
                     alpha=alpha,
                     lineend=lineend,
                     linejoin=linejoin,
                     linemitre=linemitre,
                     lex=lex,
                     pch=pch,
                     size=size,
                     addArrow=addArrow,
                     angleArrow=angleArrow,
                     lengthArrow=lengthArrow,
                     endsArrow=endsArrow,
                     typeArrow=typeArrow,
                     just=just,
                     hjust=hjust,
                     vjust=vjust,
                     rot=rot,
                     check.overlap=check.overlap,
                     clip=clip
                     )
    
    defaults

}
    


